// src/pages/About.vue
<template>
  <div class="ph4 mt5">
        <h1 class="f2 mv0 lh-copy fw3 ttu">About</h1>
    <section class="fw2 lh-copy">
        <p>Since a very young age, Ollie has had three passions; Music, Art and Fashion. Creativity is something that is incorporated into his everyday routine, and has become part of the fabric that weaves his projects together. Oliverproudlock.com is the culmination of all Oliver’s current working projects, and will be the destination for a variety of commitments, including Art, Serge DeNimes, Proudlock Style, as well as collaborations and exciting news.</p>
        <p>Since leaving Newcastle University, where Ollie completed a degree in Fine Art, he has continued in his mother’s footsteps making the move into fashion. Moving back to London, Oliver set up Serge DeNimes, a design-led brand that presents an exclusive collection of fashion and accessories. Serge focuses on premium, urban apparel of the highest quality. Their original designs epitomize the urban culture and artistic flair that is the foundation of the Serge lifestyle. We strive to create an artistic community that focuses on producing cutting edge designs. In addition to exciting progression within his own brand, Oliver has collaborated on a number of projects. Oliver has designed an exclusive range of 4 styles of shoe for popular brand Oliver Sweeney. The shoe range was sold online, as well in all Oliver Sweeney stores within the UK and one of London’s largest retailers Harvey Nichols.</p>
        <p>He also has collaborated with English jewelry designer Theo Fennell, and created a capsule collection made up of necklaces, bracelets, and earrings with a Native Indian theme.</p>
        <p>One other main passion that has really developed over the last two years, since he completed a gruelling 6 week muscle plan that was figured in Mens Health, is fitness/health and nutrition. Ever since he has continued to keep in shape, releasing his own fitness book called ‘6 Week Muscle Plan’.</p>
        <p>If you wish to keep unto date with all Ollie’s past, present and future projects this is the place to be. Everything from fashion, music, art, style and fitness will be posted on this site.</p>
        <p>Hope you enjoy!!</p>
    </section>
  </div>
</template>

// src/pages/about.tsx
// tslint:disable:max-line-length
import * as React from 'react'

import Page from '../components/page'
import { Models } from '../models'

const page: Helix.Page<Models>['view'] = (state, prev, send) => {
  return (
    <Page>
      <section className="fw2 lh-copy">
        <p>Since a very young age, Ollie has had three passions; Music, Art and Fashion. Creativity is something that is incorporated
      into his everyday routine, and has become part of the fabric that weaves his projects together. Oliverproudlock.com
      is the culmination of all Oliver’s current working projects, and will be the destination for a variety of commitments,
      including Art, Serge DeNimes, Proudlock Style, as well as collaborations and exciting news.</p>
        <p>Since leaving Newcastle University, where Ollie completed a degree in Fine Art, he has continued in his mother’s footsteps
      making the move into fashion. Moving back to London, Oliver set up Serge DeNimes, a design-led brand that presents
      an exclusive collection of fashion and accessories. Serge focuses on premium, urban apparel of the highest quality.
      Their original designs epitomize the urban culture and artistic flair that is the foundation of the Serge lifestyle.
      We strive to create an artistic community that focuses on producing cutting edge designs. In addition to exciting progression
      within his own brand, Oliver has collaborated on a number of projects. Oliver has designed an exclusive range of 4
      styles of shoe for popular brand Oliver Sweeney. The shoe range was sold online, as well in all Oliver Sweeney stores
      within the UK and one of London’s largest retailers Harvey Nichols.</p>
        <p>He also has collaborated with English jewelry designer Theo Fennell, and created a capsule collection made up of necklaces,
      bracelets, and earrings with a Native Indian theme.</p>
        <p>One other main passion that has really developed over the last two years, since he completed a gruelling 6 week muscle
      plan that was figured in Mens Health, is fitness/health and nutrition. Ever since he has continued to keep in shape,
      releasing his own fitness book called ‘6 Week Muscle Plan’.</p>
        <p>If you wish to keep unto date with all Ollie’s past, present and future projects this is the place to be. Everything
      from fashion, music, art, style and fitness will be posted on this site.</p>
        <p>Hope you enjoy!!</p>
      </section>
    </Page>
  )
}

export default page
