// src/components/post.vue
<template>
  <article class="post">
    <router-link v-if="excerpt" :to="`/posts/${category}/${post.ID}`" class="link black">
      <h1 class="f2 mv0 lh-copy fw3 ttu">{{ post.title }}</h1>
    </router-link>
    <h1 v-if="!excerpt" class="f2 mv0 lh-copy fw3 ttu">{{ post.title }}</h1>

    <time v-if="post.date" :datetime="post.date" itemprop="datePublished">{{ post.date }}</time>
    <section class="fw2 lh-copy" v-html="excerpt ? post.excerpt : post.content"></section>
  </article>
</template>

<script>
  export default {
    props: {
      excerpt: {
        type: Boolean,
        default: false,
      },
      post: {
        type: Object,
        required: true,
      },
    },

    computed: {
      category () {
        const categories = Object.keys(this.post.categories)
        return categories.length ? this.post.categories[categories[0]].slug : 'uncategorized'
      },
    },
  }
</script>

<style>

</style>

// src/pages/post.tsx
// tslint:disable:max-line-length
import * as React from 'react'

import Page from '../components/page'
import { Models } from '../models'
import NotFound from './not-found'

const page: Helix.Page<Models>['view'] = (state, prev, send) => {
  if (!state.posts.posts.length) {
    return ''
  }

  const post = state.posts.posts.find(p => p.slug === state.location.params.slug)
  if (!post) {
    send.app.setPageTitle('Not Found')
    return NotFound()
  }

  send.app.setPageTitle(post.title)
  return (
    <Page>
      <h1 className="f4 mv0 lh-copy fw3 ttu" dangerouslySetInnerHTML={{ __html: post.title }} />
      <time
        dateTime={post.date}
        itemProp="datePublished"
        className="sans-serif f6 gray mb3 db"
      >
        {post.date.slice(0, 10)}
      </time>
      <section className="fw2 lh-copy post-content" dangerouslySetInnerHTML={{ __html: post.content }} />
    </Page>
  )
}
export default page
