// src/pages/Posts.vue
<template>
  <div class="ph4 mt5 mw9">
    <p v-if="!posts.length && !$store.state.loading">No Posts</p>

    <transition-group name="fade">
      <article v-for="post in posts" :key="post.slug">
        <router-link :to="`/posts/${category}/${post.ID}`" class="link black">
        <h1 class="f2 mv0 lh-copy fw3 ttu">{{ post.title }}</h1>
        </router-link>
        <time v-if="post.date" :datetime="post.date" itemprop="datePublished">{{ post.date }}</time>
        <section class="fw2 lh-copy" v-html="post.excerpt">
        </section>
      </article>
    </transition-group>

  </div>
</template>

<script>
  export default {
    mounted () {
      this.fetchPosts()
    },
    computed: {
      category () {
        return this.$route.params.category
      },
      posts () {
        return this.$store.state.posts
      },
    },
    methods: {
      fetchPosts () {
        if (!this.posts.length || this.category !== this.$store.postCategory) {
          this.$store.commit('setLoading', {loading: true})
          this.$store.dispatch('getPosts', {category: this.category})
        }
      },
    },
    watch: {
      category () {
        this.fetchPosts()
      },
    },
  }
</script>

// src/pages/posts.tsx
import * as React from 'react'

import Page from '../components/page'
import { Models } from '../models'
import { filterPostsByCategory } from '../services/posts'

const page: Helix.Page<Models>['view'] = (state, prev, send) => {
  if (!state.posts.posts.length) {
    return <Page><span>No Posts Here</span></Page>
  }
  const category = state.location.params.category
  const posts = filterPostsByCategory(state.posts.posts, category)

  send.app.setPageTitle(`${category} | Posts`)
  return (
    <Page>

      {posts.map((post, index) => (
        <article className={`cb pv4 ${index > 0 ? ' bt' : ''}`} key={index}>
          <a
            href={`/posts/${category}/${post.slug}`}
            className="db fl-ns w-30-ns w-50-l mw6 pr3-ns pb0-ns pb3">
            <img src={post.post_thumbnail.URL} alt={post.title} className="db" />
          </a>

          <a
            href={`/posts/${category}/${post.slug}`}
            className="black link"
          >
            <h1
              className="f4 mv0 lh-copy fw3 tracked-tight dim"
              dangerouslySetInnerHTML={{ __html: post.title }}
            />
          </a>
          <time
            dateTime={post.date}
            itemProp="datePublished"
            className="sans-serif f6 gray mb3 db"
          >
            {post.date.slice(0, 10)}
          </time>
          <section className="fw2 lh-copy post-content" dangerouslySetInnerHTML={{ __html: post.excerpt }} />
          <div className="cb" />
        </article>
      ))}
    </Page>
  )
}
export default page
